---
title: "What is your blogpost title? Add it here??"
subtitle: "Assignment 4 ETC5512"
author: "Who are you?? Add your name here"
format: html
editor: visual
---

::: panel-tabset
<!-- Task 1 Tab: Data and Documenting -->

## Data and Documenting

1.  **Research Question**

    How is AI exposure distributed across occupations and demographic groups in Australia?

    **Motivation**

    Generative AI has rapidly become one of the most significant technological developments shaping the world and particularly modern workplaces. More than 50% of organisations in Australia have reportedly integrated AI into their operations (CSIRO, 2025), and the adoption of AI is expected to continue rising with significant impact across different occupations and industries. Jobs and Skills Australia (2025) identifies generative AI as a major force likely to influence the Australian labour market, with effects depending on occupational tasks, workplace adoption, and workforce adaptation.

    Understanding AI exposure is becoming increasingly important as the impacts of AI use are likely to be unevenly distributed across the workforce. Jobs and Skills Australia (2025) suggests that generative AI is more likely to augment human work than replace it, where the greatest potential for automation is concentrated in more routine tasks. The report also highlighted substantial differences in AI exposure across occupations, indicating that some workers may experience greater changes to their work than others.

    This topic was chosen because it combines a highly relevant contemporary issue with publicly available Australian labour market data and demographic census data. By examining how AI exposure is distributed across occupations and demographic groups, the analysis aims to identify which workers may be most affected by technological change and contribute to broader discussions about workforce adaptation, training needs, and future employment opportunities.

<!-- Task 2 Tab: Writing your blogpost -->

## Blog post

### What's in this section

Here is where you should write your blogpost! (Task 2)

### Blogpost Structure

There is no strict structure for you to follow. However, here is a skeleton structure you may find helpful.

1.  Title (is set at the top of this document)
2.  Motivation\
3.  Data\
4.  Analysis\
5.  Conclusions\
6.  References

<!-- Task 3 Tab: Behind the Scenes -  -->

## Behind the Scenes

### What's in this section

Here is where you should tell us about your reflection on your analysis (Task 3).

Again, these are the details about **your** perspective and the gritty details behind the scenes of your analysis.
:::
